JobPortal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from JobPortal import settings

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path, include
from . import views

urlpatterns = [

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.safestring import mark_safe
# from location_field.models.plain import PlainLocationField
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    is_candidate = models.BooleanField(default=False)
    is_recruiter = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def name(self):
        return "%s %s" % (self.first_name, self.last_name)


class Institute(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Skill_and_Category(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class Candidate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    profile_pic = models.ImageField(upload_to="images/profile", null=True,
                                    default="../static/images/avatar.png", blank=True)
    institute_name = models.ForeignKey(to=Institute, on_delete=models.CASCADE, null=True)
    institute_certificate = models.ImageField(upload_to="images/certificate", null=False, blank=False)
    phone = PhoneNumberField(null=False, blank=False)
    # year_of_passing = models.DateField(null=True, blank=True)
    Experience = models.PositiveIntegerField(default=0, blank=True)
    Skills = models.ManyToManyField(to=Skill_and_Category, related_name="skill")
    ctc = models.IntegerField(null=True, blank=True)
    about = models.CharField(null=True, blank=True, max_length=300)

    def __str__(self):
        return self.user.username

    def fullname(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def candidateemail(self):
        return self.user.email

    def is_active(self):
        return self.user.is_active

    def user_pic(self):
        if self.profile_pic.url is not None and self.user.is_active:
            return mark_safe(
                '<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">' + '<a href="{}">'.format(
                    self.profile_pic.url) + '<div class="relative w-12 h-12">' + '<img src="{}" alt="Avatar" class="rounded-full w-full h-full" />'.format(
                    self.profile_pic.url)
                + '<div class="absolute w-4 h-4 right-0 bottom-0 rounded-full bg-blue-400 text-white text-xs text-center leading-4">' + '✓</div>'
                + '</div>' + '</a>')
        elif self.profile_pic.url is not None:
            return mark_safe(
                '<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">' + '<a href="{}">'.format(
                    self.profile_pic.url) + '<div class="relative w-12 h-12">' + '<img src="{}" alt="Avatar" class="rounded-full w-full h-full" />'.format(
                    self.profile_pic.url)
                + '</div>' + '</a>')

    def institute_certificate_img(self):
        if self.institute_certificate.url is not None:
            return mark_safe(
                '<a href="{}">'.format(self.institute_certificate.url) + '<img src="{}" height="50"/>'.format(
                    self.institute_certificate.url) + '</a>')

    def Skill(self):
        return "\n , ".join([s.name for s in self.Skills.all()])


class Recruiter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone_number = models.CharField(max_length=20)
    company_name = models.CharField(max_length=60)
    company_description = models.CharField(max_length=300)

    def __str__(self):
        return self.user.username

    def fullname(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def is_active(self):
        return self.user.is_active


class RecruiterPosting(models.Model):
    user = models.ForeignKey(Recruiter, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=200, default='', blank=True)

    job_title = models.CharField(max_length=200)
    # location = PlainLocationField(based_fields=['location'], zoom=7)
    job_description = models.CharField(max_length=1000)
    JOB_TYPE = (
        ('Full time', 'Full time'),
        ('Internship', 'Internship'),
    )
    job_type = models.CharField(choices=JOB_TYPE, max_length=100)
    ctc = models.CharField(max_length=200)
    skills = models.ForeignKey(Skill_and_Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.job_title


class CandidateApply(models.Model):
    cand = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    apply = models.ForeignKey(RecruiterPosting, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, default='pending')

    def __str__(self):
        return self.cand.user.username

    def Skill(self):
        return "\n , ".join([s.name for s in self.cand.Skills.all()])

templates/all_posting.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
       <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- google font -->
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
      rel="stylesheet"
    />
    <!-- font awsome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
        <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
      <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- custom css -->
    <link rel="stylesheet" href="./css/result.css" />
    <!-- responsive css -->
          <link rel="stylesheet" type="text/css" href="{% static 'css/all_posting.css' %}"/>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

      <style>

          hr.style-six {
padding: 0;
border: none;
height: 1px;
background-image: -webkit-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
background-image: -moz-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
background-image: -ms-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
background-image: -o-linear-gradient(left, rgba(0,0,0,0), rgba(0,0,0,0.75), rgba(0,0,0,0));
color: #333;
text-align: center;
}
hr.style-six:after {
content:" ";
display: inline-block;
position: relative;
top: -2.1em;
font-size: 1.5em;
padding: 19px 1.75em;
background: #fff url() no-repeat scroll center;
background-size: 90px 90px;
height: 50px;
}


          a {
  text-decoration: none;
  display: inline-block;
  padding: 8px 16px;
}



.previous {
  background-color: lightgray;
  color: black;
}

.next {
  background-color: #04AA6D;
  color: white;
}

.round {
  border-radius: 50%;
}

.span{
    font-size: 13px;
}

.button {
    display: block;

    color: #f2f2f2;
    background-color: #ff8149;
    text-decoration: none;
    padding: 0.7rem 0;
    text-align: center;
    margin-left: 1rem;
    margin-top: 1rem;
    font-weight: 800;
    border-radius: 35px;
}

        .button {
        width: 200px;
        margin: 1.1rem auto;
        font-size: 1.2rem;
    }
    .linked{
    text-color: green;

    }
    a: hover{
    color: green;
    background-color:black;
    }
.myjob{
font-size:22px!important;
font-weight: bold;!important;
}
.isize{
font-size:15px;
}
.detail{
font-size:18px;
float:right;
margin:5px;
}
.stas{
list-style:nine;
text-decoration:none;
}
      </style>


    <title>Jobs Result</title>
  </head>
  <body>

{% block content %}
        <!----------------- navbar-start ---------------->
    <div class="navbar-area">
      <div class="container">
          <div class="main-menu">
              <div class="logo-area">
                  <a href="#"><img src="{% static 'images/logo.png' %}" alt="Logo"></a>
              </div>
              <div class="menu-area">
                  <ul>


                      <li><a style="font-weight: bold" href="{% url 'all_posting' %}">My Jobs</a></li>
                      <li><a style="font-weight: bold" href="{% url 'contact' %}">Contact Us</a></li>
                      <li><a style="font-weight: bold" href="{% url 'logout' %}">LOGOUT</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>

      <!--------------------- navbar-end --------------------->
  <p class="resss">Filter Jobs</p>
    <div class="container">
      <div class="row">
          <div class="col-md-2"></div>
             <div class="col-md-9">
        <div class="right-section">

          <div class="r-heading">
            <p></p>
            <div class="short-by">
                <br>
              <p>Sort by</p>
              <select style="font-size: 11px" name="#" id="#">
                <option value="#" selected style="font-size: 11px">Relevance</option>
                <option value="#" style="font-size: 11px">Newst arrival</option>
              </select>
            </div>

          </div><br><br>

<div class="card" style="border-radius:2%;">

  <div class="card-header myjob" style=" background-color:#D3D3D3;!important">
      <img src="{% static 'images/company_logo.jfif' %}" style="border-radius:40%;" alt="#">
<!--    {{ data.apply.user.company_name }}-->OneSkill
            <a class="btn btn-primary" style="font-size:16px;color:red;float:right;background-color:#fff;padding:4px;border-radius:6px;border-color:red;">Delete</a>

  </div>

  <div class="card-body" style="width:100%;">
    <h3 class="card-title">hamza</h3>
    <ol>
              <li>
                <i class="fas fa-search-location isize"></i>
                  <a class="isize">hnd</a>
              </li>
              <li><i class="far fa-clock isize"></i><a href="#" class="isize">internship</a></li>

            </ol>
           <h4 style="font-weight: bold">Description</h4>
            <ul>
              <li style="font-size: 13px">my job</li><br>
                <li><h5 class="fa fa-dollar" style="font-size: 13px">&nbsp;CTC = 12345</h5></li><br>

                            </ul>
       <h4 style="font-weight: bold">Skills</h4>
                            <ul>
              <li style="font-size: 13px">html</li>
                                                            </ul>

  </div>

</div> <br><hr class="style-six"><br>
            </div></div></div>
          <!-- first option -->

<!--            {% for data in posts %}-->
<!--          <div class="part-1" style=" border-radius: 30px;">-->
<!--            <div class="logo-com">-->
<!--              <img src="{% static 'images/company_logo.jfif' %}" alt="#"/>-->
<!--             <p style="font-weight: bold">{{ data.apply.user.company_name }}</p>-->


<!--            </div>-->
<!--<br>-->

<!--              <h4 class="linked" style="font-weight: bold">&ensp;&ensp;{{data.apply}}</h4>-->
<!--            <ol>-->
<!--              <li>-->
<!--                <i class="fas fa-search-location"></i>-->
<!--                  <a>{{ data.apply.location }}</a>-->
<!--              </li>-->
<!--              <li><i class="far fa-clock"></i><a href="#">{{ data.apply.job_type }}</a></li>-->
<!--                <li><i class="far fa-clock"></i><a href="#">{{ data.status }}</a></li>-->
<!--            </ol>-->

<!--            <h4 style="font-weight: bold">Description</h4>-->
<!--            <ul>-->
<!--              <li style="font-size: 13px">{{ data.apply.job_description }}</li><br>-->
<!--                <li><h5 class="fa fa-dollar" style="font-size: 13px">&nbsp;CTC = {{ data.apply.ctc }}</h5></li><br>-->

<!--                            </ul>-->

<!--                            <h4 style="font-weight: bold">Skills</h4>-->
<!--                            <ul>-->
<!--              <li style="font-size: 13px">{{ data.Skill }}</li>-->
<!--                                                            </ul>-->
<!--<br>-->

<!--          </div>-->
<!--            <br><br>-->
<!--                <hr class="style-six">-->
<!--            {% endfor %}-->


<br><br><br>
        {% if posts.paginator.num_pages > 1 %}

    {% if posts.has_previous %}

        <a href="?page={{ posts.previous_page_number }}" class="previous">&laquo; Previous</a>&nbsp;&nbsp;&nbsp;

    {% endif %}

    <span class="span">Page {{ posts.number }} of {{ posts.paginator.num_pages }}</span>&nbsp;&nbsp;&nbsp;

    {% if posts.has_next %}

        <a href="?page={{ posts.next_page_number }}" class="next">Next &raquo;</a>

    {% endif %}

{% endif %}

    <footer>
      <ul>
        <li><a href="#">Terms of Service</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Trust & Safety</a></li>
      </ul>
    </footer>
  </body>
</html>
{% endblock %}

templates/candidate_register.html
{% load widget_tweaks %}
 {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
       {{ form.media }}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <!-- Select2-->

 <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register as a Candidate</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'candidate_register' %}" method="POST"  enctype="multipart/form-data" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>



<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
    $('#id_skills').select2();
});
</script>
</body>
</html>

templates/candidate_update.html
{% load widget_tweaks %}
 {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
       {{ form.media }}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <!-- Select2-->

 <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register as a Candidate</h2>
                </div>
                <div class="card-body">
                    <form action=" " method="POST"  enctype="multipart/form-data" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                             <input type="submit" value="Update" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>



<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
    $('#id_Skills').select2({
    width: 'resolve'
    });
});
</script>
</body>
</html>

templates/login.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Registration</title>
</head>
<body>
<br><br><br><br><br><br><br>
    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Login</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'login' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% if messages%}
                                      {% for message in messages %}
                                        <span style="color:red">{{ message }}</span>
                                      {% endfor %}
                                     {% endif %}
                         {% endfor %}
                         <br>


                             <input type="submit" value="Login" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>

templates/recruiter_posting2.html
{% load widget_tweaks %}
 {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
       {{ form.media }}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <!-- Select2-->

 <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
<body>

    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register as a Candidate</h2>
                </div>
                <div class="card-body">
                    <form action="" method="POST"  enctype="multipart/form-data" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                               <br><br><br>
                             <input type="submit" value="Post Job" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>   
                </div>
              </div>
            </div>
        </div>
      </section>



<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
    $('#id_skills').select2();
});
</script>
</body>
</html>

templates/recruiter_register.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <title>Recruiter Registration</title>
</head>
<body>
    <section>
        <div class="container">
          <div class="row">
            <div class="col-md-6 mx-auto">
              <div class="card">
                <div class="card-header text-black">
                  <h2>Register as a Recruiter</h2>
                </div>
                <div class="card-body">
                    <form action="{% url 'recruiter_register' %}" method="POST" novalidate>
                      {% csrf_token %}
                         {% for field in form.visible_fields %}
                           <div class="form-group">
                               {{ field.label_tag }}
                                  {% render_field field class="form-control" %}
                                    {% for error in field.errors %}
                                      <span style="color:red">{{ error }}</span>
                                    {% endfor %}
                         {% endfor %}
                    <br>
                             <input type="submit" value="Register" class="btn btn-block btn-primary">
                           </div>
                    </form>
                 </div>
                    </div>
                </div>
              </div>
            </div>
        </div>
      </section>

</body>
</html>